### ISSUE TITLE
SpringBoot: Zuul 文件上传问题，小文件可以，大一点的就不行

### ISSUE THREAD

**Issue by BruceOuyang** [BruceOuyang/issuelist#1]
## Solution： 设置zuul文件大小限制
在yml配置文件中，添加如下配置，按需调整下边的size
```
spring:
  http:
    multipart:
      max-file-size: 10Mb
      max-request-size: 10Mb 
```
