### ISSUE TITLE
docker 运行常见中间件

### ISSUE THREAD

**Issue by BruceOuyang** [BruceOuyang/issuelist#58]
# docker 运行 nginx
```
docker run -d -p 8090 --name boy-nginx -v /opt/nginx/www:/usr/share/nginx/html -v /opt/nginx/conf/nginx.conf:/etc/nginx/nginx.conf -v /opt/nginx/logs:/var/log/nginx nginx
```

> 参考：https://www.runoob.com/docker/docker-install-nginx.html

**Comment by BruceOuyang** [comment]
# docker 运行 mysql
在本地创建好挂载目录
```
mkdir -p /opt/mysql/data /opt/mysql/logs /opt/mysql/conf
```

执行命令启动mysql
```
docker run -d -p 3306:3306 --name boy-mysql -e MYSQL_ROOT_PASSWORD=root -v /opt/mysql/conf:/etc/mysql/conf.d -v /opt/mysql/logs:/logs -v /opt/mysql/data:/var/lib/mysql --restart=always mysql
```

进入容器，设置mysql的远程登录账号
```
# 进入容器
docker exec it boy-mysql bash

# 登录mysql
mysql -uroot -proot

# 创建远程登录账户
CREATE USER 'bruce'@'%' IDENTIFIED WITH mysql_native_password BY 'bruce';

# 对新创建的账户授权
GRANT ALL PRIVILEGES ON *.* TO 'bruce'@'%';
```

**Comment by BruceOuyang** [comment]
# docker 运行 mongodb
在本地创建好挂载目录
```
mkdir -p /opt/mongodb/data /opt/mongodb/conf /opt/mongodb/logs
```

执行命令运行 mongodb
```
docker run -d -p 27017:27017 --name boy-mongo -v /opt/mongodb/data:/data/db -e MONGO_INITDB_ROOT_USERNAME=root-e MONGO_INITDB_ROOT_PASSWORD=root mongo
```

**Comment by BruceOuyang** [comment]
# docker 运行 redis
在本地创建好挂载目录
```
mkdir ...
```
执行命令运行 redis
```
docker run -d -p  ...
```

**Comment by BruceOuyang** [comment]
### docker-compose “一键方案”

在脚本目录下执行命令
```
docker-compose up -d
```

docker-compose.yaml 脚本
```
version: "3"

services:
  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    container_name: boy-mysql
    volumes:
      - ./components/mysql/data:/var/lib/mysql
      - ./components/mysql/conf:/etc/mysql/conf.d
      - ./components/mysql/logs:/logs
      - /etc/localtime:/etc/localtime
    environment:
      MYSQL_ROOT_PASSWORD: root
      EXTRA_OPTS: lower_case_table_names=1
    restart: always

  mongodb:
    image: mongo
    ports:
      - 27017:27017
    container_name: boy-mongo
    volumes:
      - ./components/mongodb/data:/data/db
    environment:
      TZ: Asia/Shanghai
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    restart: always

  redis:
    image: redis
    ports:
      - 6379:6379
    container_name: boy-redis
    volumes:
      - ./components/redis/data:/data
      #redis config file
      #- ./components/redis/config/redis.conf:/usr/local/redis/config/redis.conf
    environment:
      TZ: Asia/Shanghai
    restart: always
    sysctls:
      net.core.somaxconn: 1024
    command: redis-server --requirepass root --appendonly yes


  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181
    container_name: boy-zk
    volumes:
      - /etc/localtime:/etc/localtime
    environment:
      TZ: Asia/Shanghai
    restart: always
```
