### ISSUE TITLE
解决mysql java.sql.SQLException: The server time zone value‘XXXXXX' is unrecognized or represents...

### ISSUE THREAD

**Issue by BruceOuyang** [BruceOuyang/issuelist#62]
> 引用：[CodDog的博文](https://luoliangdsga.github.io/2016/08/09/Mybatis%E4%BD%BF%E7%94%A8MySQL%E4%B8%AD%E9%81%87%E5%88%B0%E7%9A%84%E4%B8%80%E4%B8%AA%E9%97%AE%E9%A2%98/)

解决mysql java.sql.SQLException: The server time zone value‘XXXXXX' is unrecognized or represents...
![image](https://user-images.githubusercontent.com/5382942/72168239-b7208a80-3407-11ea-9ef1-823124dca303.png)

使用的数据库是MySQL，驱动是6.0.3，这是由于数据库和系统时区差异所造成的，在jdbc连接的url后面加上serverTimezone=GMT即可解决问题，如果需要使用gmt+8时区，需要写成GMT%2B8，否则会被解析为空。再一个解决办法就是使用低版本的MySQL jdbc驱动，5.1.28不会存在时区的问题。

url 示例
```
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/staffjoy_account?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: root
  jpa:
    show-sql: true
```
